export const ADD_DESTINATION = 'ADD_DESTINATION';
export const FETCH_COUNTRIES_FAILED = 'FETCH_COUNTRIES_FAILED';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const ADD_JOURNEY = 'ADD_JOURNEY';
